#!/usr/bin/env bash
# pin-digests.sh — Pull every image declared in .env and record their
# immutable SHA-256 content digests in digests.lock.
#
# Usage:
#   scripts/pin-digests.sh [ENV_FILE]
#
# Arguments:
#   ENV_FILE  Path to the env file that declares *_IMAGE variables.
#             Defaults to .env in the repository root.
#
# Output:
#   digests.lock  Written (or overwritten) in the repository root.
#                 Each line: <image-reference> <sha256-digest>
#                 Use scripts/verify-images.sh to validate against this file.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${1:-"$REPO_ROOT/.env"}"
LOCK_FILE="$REPO_ROOT/digests.lock"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: env file not found: $ENV_FILE" >&2
  exit 1
fi

# get_digest IMAGE — extract the registry SHA-256 content digest for an image
# that is already present in the local Docker cache.
# Prefers RepoDigests (registry-authoritative); falls back to the image ID
# for local builds or mirrors that do not populate RepoDigests.
get_digest() {
  local img="$1"
  local digest
  digest=$(
    docker inspect --format \
      '{{range .RepoDigests}}{{.}}{{"\n"}}{{end}}' \
      "$img" 2>/dev/null \
      | grep -oE 'sha256:[a-f0-9]{64}' \
      | head -1
  )
  if [[ -z "$digest" ]]; then
    digest=$(
      docker inspect --format '{{.Id}}' "$img" 2>/dev/null \
        | grep -oE 'sha256:[a-f0-9]{64}' \
        | head -1
    )
  fi
  echo "$digest"
}

# Collect unique image references from *_IMAGE variables in the env file.
mapfile -t IMAGES < <(
  grep -E '^[A-Z_]+_IMAGE=' "$ENV_FILE" \
    | sed 's/^[^=]*=//' \
    | sort -u
)

if [[ ${#IMAGES[@]} -eq 0 ]]; then
  echo "ERROR: no *_IMAGE variables found in $ENV_FILE" >&2
  exit 1
fi

echo "Pinning ${#IMAGES[@]} image(s) from $ENV_FILE ..."
echo

TMP_LOCK="$(mktemp)"
trap 'rm -f "$TMP_LOCK"' EXIT

{
  echo "# Generated by scripts/pin-digests.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  echo "# Source: $ENV_FILE"
  echo "# Format: <image-reference> <sha256-digest>"
  echo "#"
  echo "# DO NOT EDIT MANUALLY — regenerate with: scripts/pin-digests.sh"
  echo ""
} >> "$TMP_LOCK"

FAILED=0

for image in "${IMAGES[@]}"; do
  printf "  %-60s " "$image"

  if ! docker pull --quiet "$image" >/dev/null 2>&1; then
    echo "PULL FAILED"
    FAILED=$((FAILED + 1))
    continue
  fi

  digest=$(get_digest "$image")

  if [[ -z "$digest" ]]; then
    echo "DIGEST NOT FOUND"
    FAILED=$((FAILED + 1))
    continue
  fi

  echo "$digest"
  echo "$image $digest" >> "$TMP_LOCK"
done

if [[ $FAILED -gt 0 ]]; then
  echo ""
  echo "ERROR: $FAILED image(s) could not be pinned. digests.lock was NOT updated." >&2
  exit 1
fi

mv "$TMP_LOCK" "$LOCK_FILE"
echo ""
echo "digests.lock written with ${#IMAGES[@]} pinned image(s)."
echo "Commit digests.lock and use scripts/verify-images.sh before starting the stack."
